export const URL_LIST = 'https://api.themoviedb.org/3/discover/movie';
export const URL_SEARCH = 'https://api.themoviedb.org/3/search/movie?query=';
export const URL_DETAIL = 'https://api.themoviedb.org/3/movie/';
export const URL_IMG = 'https://image.tmdb.org/t/p/';
export const IMG_SIZE_XSMALL = 'w45/';
export const IMG_SIZE_SMALL = 'w300/';
export const IMG_SIZE_LARGE = 'w342/';
export const API_KEY = '?api_key=3a1dbcc58d046ff20488384f3e79b85b';
export const API_KEY_ALT = '&api_key=3a1dbcc58d046ff20488384f3e79b85b';